const DATE_FORMAT = "DD/MM/YYYY";
const DATE_TIME_FORMAT = "DD/MM/YYYY HH:mm:ss";
const ISO_DATE_FORMAT = "YYYY-MM-DD";
const ISO_DATE_TIME_FORMAT = "YYYY-MM-DD HH:mm:ss";
export { ISO_DATE_FORMAT, DATE_FORMAT, DATE_TIME_FORMAT, ISO_DATE_TIME_FORMAT };
